server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # cache leve para JS, sem cache para HTML
    location ~* \.js$ {
        add_header Cache-Control "public, max-age=3600";
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
